spring:
    application:
        name: graphql
    datasource:
        url: jdbc:mysql://localhost:3308/catalogdb
        username: devuser
        password: dev
    graphql:
        graphiql:
            enabled: true
server:
    port: 8083